DATA:
  data_root: data/matterport_3d
  data_root_2d: data/matterport_2d
  caption_path: data/caption/caption_view_matterport_vit-gpt2-image-captioning_.json
  entity_path: data/caption/small/caption_entity_matterport_vit-gpt2-image-captioning_small.json
  
  category_split: 
    novel_category: [9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20]  # 11个新类别
    ignore_category: [255]  # 背景/未知类别
    base_category: [0, 1, 2, 3, 4, 5, 6, 7, 8, 13]  # 10个基础类别
    all_category: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

  all_label: ['wall', 'floor', 'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 
             'window', 'bookshelf', 'picture', 'counter', 'desk', 'curtain', 
             'refridgerator', 'shower curtain', 'toilet', 'sink', 'bathtub', 
             'otherfurniture', 'ceiling']
  
  label: ['wall', 'floor', 'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 
          'window', 'curtain']  # 保持10个基础类别
  
  label_2d: [1, 2, 3, 4, 5, 6, 7, 8, 9, 16]  # 对应基础类别的2D标签映射

  test_ignore_label: [255]  # 测试时忽略背景类别
  ignore_label: 21  # 总类别数（不包括背景）
  data_ratio: 0.5

  classes: 10  # 基础类别数量保持不变
  test_classes: 21  # 总类别数量（包括所有类别）
  num_queries: 200
  scannet200: False
  scores_threshold: 0.0

  pixel_mean: [0.0, 0.0, 0.0]
  pixel_std: [255.0, 255.0, 255.0]

  aug: False
  voxel_size: 0.02
  input_color: True 
  use_shm: False
  loop: 16
  val_keep: 10000000
  
Model:
  arch_3d: MinkUNet34C
  arch_binary_head: MinkUNet18A
  lseg_model_path: pretrained/weights/lseg/demo_e200.ckpt

  start_contra: 0
  binary_2d_thresh: 0.5
  scores_keep_thresh: 0
  
  lr_3d: 0.0001
  lr_others: 0.0001
  weight_decay: 0.00001
  warmup_epochs: 2
  prompt_eng: True

  loss_weight:
    loss_3d: 4
    loss_3d_pure: 4
    loss_3d_contra: 1.2  # 轻微调高，因为新类别增加
    loss_explicit_contra: 1.5
    loss_explicit_contra_3d: 1.5
    loss_explicit_contra_2d_pre: 4
    loss_binary: 12  # 适度提高，因为类别数量增加
    pseudo_label: 1
    entity_gt_loss: 1.5

  pseudo_label:
    enable: True
    temperature: 0.07  
    scores_keep_thresh: 0.05
    infer_use_caption_boost: True
    infer_caption_boost_factor: 0.3
    infer_boost_only_novel_pred: False
    use_view_entities: True
  
  entity_gt:
    enable: True
    contrastive_temp: 0.07

  cam:
    enable: True
    alignment_dim: 512
    loss_weight: 1.5
    kl_temperature: 1.2

  mask_contra_3d: True
  caption_contra: True
  caption_contra_2d_pre: True
  caption_contra_3d: True
  use_ape: False

  mask_shape: [512,640]

  power: 0.9
  momentum: 0.9
  manual_seed: 5557 
  print_freq: 10
  save_freq: 1
  eval_freq: 2
  base_ratio: 0.65
  novel_ratio: 0.25  # 适度提高，因为新类别比例增加
  clip_name: "ViT-L-14"
  learning_rate_type: cosine

Distributed:
  save_path: 
  resume:                   # 留空或填写恢复训练的 checkpoint 文件路径
  dist_url: tcp://127.0.0.1:6745
  dist_backend: 'nccl'
  multiprocessing_distributed: False  # 单 GPU 不需要多进程分布式
  world_size: 1              # 使用的 GPU 总数为 1
  rank: 0                    # 单 GPU 的 rank 为 0
  train_gpu: [0]             # 使用 GPU 0
  workers: 1                 # 数据加载的子进程数量
  batch_size: 4             # 根据显存调整训练的 batch size
  batch_size_val: 1          # 验证时的 batch size
  infer_gpu: [0]             # 推理时使用 GPU 0
  infer_workers: 0           # 推理时的数据加载子进程
  infer_batch_size_val: 1    # 推理时的 batch size
  evaluate: True             # 是否评估模型
  train_s: True              # 是否训练模型
  epochs: 100                # 训练的总 epoch 数
  start_epoch: 0             # 训练的起始 epoch
